---
randomizer:
  name: "default"
  seed: 0
memory: 100000
reclaimer:
  name: "fault-aging"
  thresholdHigh: 0.75
  thresholdLow: 0.7
instruction-set: !<is2>
  stack-size: 10
  ip-randomizer: !<fade>
    probability: 10
    distance: 5
  randomizers:
    INCREMENT: !<shift>
      probability: 200
      value: 2
    JUMP: !<fade>
      probability: 10
      distance: 10
    FIND: !<fade>
      probability: 10
      distance: 10
    DECREMENT: !<shift>
      probability: 200
      value: 2
    WRITE: !<shuffle>
      probability: 100
      range: "BYTE"
  cost-unknown: 15
  cost-default: 5
  gain-per-cycle: 10
  initial-energy: 200
  costs:
    FAULT: 15
    DECREMENT: 4
    ALLOC: 58
    FIND: 4
    FORK: 14
    PUSH: 3
    POP: 7
    DUP: 7
    DROP: 3
    JUMP: 3
    LABEL: 6
    IF: 2
    WRITE: 2
    SUBSTRACT: 9
    ADD: 9
    RESET: 3
    INCREMENT: 6
    READ: 6
    NOP: 1
    SWAP: 7
  bootstraps:
  - code:
    - "label0"
    - "find_forward_label0"
    - "increment"
    - "dup"
    - "pop_S"
    - "find_backward_label0"
    - "substract"
    - "dup"
    - "pop_V"
    - "dup"
    - "alloc"
    - "add"
    - "pop_D"
    - "push_0"
    - "label1"
    - "drop"
    - "decrement_S"
    - "decrement_D"
    - "decrement_V"
    - "push_S"
    - "read"
    - "push_D"
    - "write"
    - "push_V"
    - "if_not_null"
    - "go_backward_to_label1"
    - "fork"
    - "reset"
    - "label0"
  - code:
    - "label0"
    - "find_forward_label0"
    - "increment"
    - "dup"
    - "pop_S"
    - "find_backward_label0"
    - "substract"
    - "dup"
    - "pop_V"
    - "dup"
    - "alloc"
    - "add"
    - "pop_D"
    - "push_0"
    - "go_backward_to_label1"
    - "label0"
