---
randomizer:
  name: "default"
  seed: 0
memory: 100000
reclaimer:
  name: "fault-aging"
  thresholdHigh: 0.75
  thresholdLow: 0.7
instruction-set: !<is2>
  stack-size: 10
  ip-randomizer: !<fade>
    probability: 10
    distance: 5
  randomizers:
    INCREMENT: !<shift>
      probability: 200
      value: 2
    JUMP: !<fade>
      probability: 10
      distance: 10
    FIND: !<fade>
      probability: 10
      distance: 10
    DECREMENT: !<shift>
      probability: 200
      value: 2
    WRITE: !<shuffle>
      probability: 100
      range: "BYTE"
  bootstraps:
  - code:
    - "label0"
    - "find_forward_label0"
    - "increment"
    - "dup"
    - "pop_S"
    - "find_backward_label0"
    - "substract"
    - "dup"
    - "pop_V"
    - "dup"
    - "alloc"
    - "add"
    - "pop_D"
    - "push_0"
    - "label1"
    - "drop"
    - "push_S"
    - "decrement"
    - "pop_S"
    - "push_D"
    - "decrement"
    - "pop_D"
    - "push_V"
    - "decrement"
    - "pop_V"
    - "push_S"
    - "read"
    - "push_D"
    - "write"
    - "find_backward_label1"
    - "push_V"
    - "if_not_null"
    - "jump"
    - "fork"
    - "reset"
    - "label0"
  - code:
    - "label0"
    - "find_forward_label0"
    - "increment"
    - "dup"
    - "pop_S"
    - "find_backward_label0"
    - "substract"
    - "dup"
    - "pop_V"
    - "dup"
    - "alloc"
    - "add"
    - "pop_D"
    - "push_0"
    - "label1"
    - "drop"
    - "decrement_S"
    - "decrement_D"
    - "decrement_V"
    - "read_at_S_write_at_D"
    - "find_backward_label1"
    - "push_V"
    - "if_not_null"
    - "jump"
    - "fork"
    - "reset"
    - "label0"
